name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # allow manual triggers
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: ['windows-latest', 'ubuntu-latest', 'macos-12']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r hatlib/requirements.txt
    - name: Unittest
      run: |
        python -m pip install -r test/requirements.txt
        python -m unittest discover test
    - name: Build whl
      run: |
        python -m pip install build
        python -m build
    - name: Install whl
      shell: pwsh
      run: |
        $WHL = Get-ChildItem -Path dist -Filter "*.whl" | %{$_.FullName}
        python -m pip install --force-reinstall $WHL
    - name: Test whl
      run: |
        cd test_acccgen
        hatlib.benchmark_hat BenchmarkHATPackage_test_benchmark.hat
